version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/ankit.squareops.xyz/
      

hooks:  
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/permission.sh
      timeout: 300
      runas: root
