version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/html/ankitword  .squareops.xyz/public_html/
      

hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/permission.sh
      timeout: 300
      runas: root
