version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/html/amiya.squareops.xyz/
      

hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/permission.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/b_install.sh
      timeout: 300
      runas: root  
