version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/html/amiya.squareops.co.in/public_html/
      

hooks:
  AfterInstall:
    - location: scripts/permission.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
